### ISSUE TITLE
companion-module-cockos-reaper

### ISSUE THREAD

**Issue by MeestorX** [LykaiosNZ/reaper-osc.js#33]
There doesn't look to be an "issues" link on that fork, so hopefully it's ok to ask here...

I'm trying to add a variable for the current playhead position, which looks to be defined here:
https://github.com/LykaiosNZ/reaper-osc.js/blob/509a7258d80da3895ce42dbd9b674b3fd969bb5e/src/Transport.ts#L36C1-L37C1

but, I cannot add the variable in the companion module. Likely doing something stupid...
It doesn't seem to recognize `'time'`. I tried `'isPlaying'` just to test, and that is working...
```
function VariableDefinitions(): ReaperPropertyVariableDefinition[] {
	const variables: ReaperPropertyVariableDefinition[] = [
		{
			variableId: 'playHeadTime',
			name: 'Playhead Time',
			getProperty: NotifyPropertySelector<Transport>((reaper) => reaper.transport, 'time'),
		}
	]
	return variables
}
```

**Comment by LykaiosNZ** [comment]
Make sure your fork is synced to the latest commit which updated `reaper-osc` to `v0.4.0` and run `yarn install` 👍

Have enabled issues there so will close this one.
